#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const read = p => JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));
const contract = read('POLICY_CONTRACT.json');
const aliases = read('ROUTING_ALIASES.json').operations;
const EFFECT={L1:1,L2:2,L3:3,L4:4}, EXP={X0:0,X1:1,X2:2,X3:3};
const catalog=Object.fromEntries(contract.routing.operation_catalog.map(x=>[x.id,x]));
const norm=s=>String(s??'').normalize('NFKC').toLocaleLowerCase().replace(/[^\p{L}\p{N}_가-힣]+/gu,' ').replace(/\s+/g,' ').trim();
function stripNegated(s){return String(s).normalize('NFKC').split(/[,;]|\bbut\b|\bhowever\b|하지만/i).filter(c=>c.trim()&&![/\bdo\s+not\b/i,/\bdon['’]?t\b/i,/\bwithout\s+(?:execut|run|deploy|publish|appl)/i,/하지\s*말/,/하지말/,/실행하지/,/하지\s*않/,/않고/,/말고/].some(r=>r.test(c))).join(' ')}
function phraseMatch(n,p){p=norm(p);if(!p)return false; if(/[가-힣]/.test(p)){const src=n.split(' '), dst=p.split(' '), particles=['은','는','이','가','을','를','에','에서','에게','께','도','와','과','로','으로','의','만','부터','까지','랑','이랑','하고'];for(let i=0;i<=src.length-dst.length;i++){if(dst.every((d,j)=>src[i+j]===d||particles.some(x=>src[i+j]===d+x)))return true}return false;} return new RegExp(`(^|\\W)${p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&').replace(/ /g,'\\s+')}($|\\W)`,'u').test(n)}
function stemMatch(n,s){s=norm(s);if(!s)return false;if(/[가-힣]/.test(s)){const src=n.split(' '), dst=s.split(' ');for(let i=0;i<=src.length-dst.length;i++){let ok=true;for(let j=0;j<dst.length-1;j++) if(src[i+j]!==dst[j]) ok=false;if(ok&&src[i+dst.length-1].startsWith(dst.at(-1)))return true;}return false;}return new RegExp(`(^|[^a-z0-9_])${s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}[a-z0-9_-]*($|[^a-z0-9_])`,'u').test(n)}
function infer(text){const n=norm(stripNegated(text));const out=[];for(const op of contract.routing.operation_catalog){const a=aliases[op.id]||{};let hit=(a.phrases||[]).some(x=>phraseMatch(n,x))||(a.stems||[]).some(x=>stemMatch(n,x));if(!hit) for(const pat of a.patterns||[]){try{if(new RegExp(pat,'u').test(n)){hit=true;break}}catch{}} if(hit)out.push(op.id)}return out}
function route(input){const mode=input.routing_mode||'advisory', rules=contract.routing.modes[mode], planned=[], canonical=[], unresolved=[];const task=infer(input.task_text||'');for(const x of task) if(!canonical.includes(x)) canonical.push(x);for(const raw of input.planned_operations||[]){const c=String(raw).trim();if(catalog[c]){if(!planned.includes(c))planned.push(c);if(!canonical.includes(c))canonical.push(c)}else{const inf=infer(c);if(inf.length)for(const x of inf){if(!planned.includes(x))planned.push(x);if(!canonical.includes(x))canonical.push(x)}else unresolved.push(c)}}const errors=[],warnings=[];if(unresolved.length)(rules.unresolved_operation_behavior==='FAIL'?errors:warnings).push('unresolved');if((input.planned_operations||[]).length&&!planned.length)(rules.unresolved_operation_behavior==='FAIL'?errors:warnings).push('none resolved');if(mode==='enforcement'&&contract.routing.enforcement_requires_resolved_plan&&!planned.length)errors.push('resolved plan required');const nt=norm(input.task_text||''), status=!nt?'EMPTY':task.length?'CLASSIFIED':'UNCLASSIFIED';if(nt&&!task.length)(rules.unclassified_task_behavior==='FAIL'?errors:warnings).push('unclassified');const gaps=(input.planned_operations||[]).length?task.filter(x=>!planned.includes(x)).sort():[];if(gaps.length)((rules.task_plan_mismatch_behavior||rules.unclassified_task_behavior)==='FAIL'?errors:warnings).push('gap');return {routing_status:errors.length?'FAIL':warnings.length?'WARN':'PASS',canonical_operations:canonical,planned_canonical_operations:planned,task_hint_status:status,task_plan_gaps:gaps,unresolved_operations:unresolved}}
function maxLevel(vals,rank){const v=vals.filter(x=>rank[x]!=null);return v.length?v.sort((a,b)=>rank[b]-rank[a])[0]:null}
function hardHints(s){const out=[];if(/\bgit\s+reset\s+--hard\b/i.test(s))out.push('git.destructive_change');if(/\bterraform\s+destroy\b/i.test(s))out.push('cloud.resource_delete');if(/\baws\s+s3\s+rm\b[^\n]*\s--recursive\b/i.test(s))out.push('storage.object_delete');if(/\b(?:drop\s+(?:table|database)|truncate\s+table)\b/i.test(s))out.push('database.destructive_change');const k=s.match(/\bkubectl\s+delete\s+([a-z0-9.-]+)\b/i);if(k)out.push(['pod','pods'].includes(k[1].toLowerCase())?'cloud.resource_change':'cloud.resource_delete');return [...new Set(out)]}
function boundary(i){const cfg=contract.execution_boundary, errors=[];const planned=(i.planned_operations||[]), actual=(i.actual_operations||[]), env=String(i.environment||'').toLowerCase();if(!i.correlation_id)errors.push('correlation');if(String(i.execution_nonce||'').length<16)errors.push('nonce');for(const x of planned)if(!catalog[x])errors.push('unknown planned');for(const x of actual)if(!catalog[x])errors.push('unknown actual');if(!actual.length)errors.push('no actual');if(actual.some(x=>(cfg.runtime_forbidden_operations||[]).includes(x)))errors.push('forbidden');if(actual.some(x=>!planned.includes(x)))errors.push('unplanned');const hh=hardHints(i.actual_action||'');if(hh.some(x=>!actual.includes(x)))errors.push('hard mismatch');if(!cfg.known_environments.includes(env))errors.push('env');let targets=[];for(const t0 of i.targets||[]){const t=String(t0).trim();if(!t||['all','any','*','everything'].includes(t.toLowerCase())||/[?*\[\]]/.test(t))errors.push('target');else if(!targets.includes(t))targets.push(t)}const valid=actual.filter(x=>catalog[x]);let effect=maxLevel(valid.map(x=>catalog[x].effect_floor),EFFECT);if(env==='production'&&cfg.production_effect_escalation_operations.some(x=>valid.includes(x)))effect='L4';if(EFFECT[i.runtime_effect]>EFFECT[effect])effect=i.runtime_effect;const sem=i.semantic_details||{};for(const rule of cfg.operation_semantic_requirements||[]){if(!rule.operations.some(x=>valid.includes(x)))continue;if(!(rule.allowed_environments||[]).includes(env))errors.push('semantic env');for(const k of rule.required_semantic_details||[])if(sem[k]==null||String(sem[k]).trim()==='')errors.push('semantic missing');for(const [k,allowed] of Object.entries(rule.semantic_detail_allowed_values||{}))if(k in sem&&!allowed.includes(sem[k]))errors.push('semantic invalid')}
const facts=i.exposure_facts;const contrib=[];if(cfg.environment_exposure_floors[env])contrib.push(cfg.environment_exposure_floors[env]);if(!facts||typeof facts!=='object'||Array.isArray(facts))errors.push('facts object');const f=facts&&typeof facts==='object'?facts:{};for(const k of cfg.exposure_derivation.required_fact_keys){if(!(k in f)){errors.push('missing fact');continue}const map=cfg.exposure_derivation.fact_floors[k];if(!(f[k] in map))errors.push('bad fact');else contrib.push(map[f[k]])}for(const k of Object.keys(f))if(!cfg.exposure_derivation.required_fact_keys.includes(k))errors.push('extra fact');let exposure=maxLevel(contrib,EXP);if(i.declared_exposure&&EXP[i.declared_exposure]!=null&&EXP[i.declared_exposure]>EXP[exposure])exposure=i.declared_exposure;for(const rule of cfg.context_effect_escalation_rules||[]){if(!rule.operations.some(x=>valid.includes(x)))continue;let match=false;for(const m of rule.match_any||[]){let v=m.source==='environment'?env:m.source.startsWith('exposure_facts.')?f[m.source.split('.')[1]]:undefined;if((m.values||[]).includes(v)){match=true;break}}if(match&&EFFECT[rule.effect]>EFFECT[effect])effect=rule.effect}
if((cfg.target_required_effect_levels||[]).includes(effect)&&!targets.length)errors.push('effect target');if((cfg.target_required_exposure_levels||[]).includes(exposure)&&!targets.length)errors.push('exposure target');let gate=null,decision='BLOCK_POLICY_ERROR';if(!errors.length&&effect&&exposure){gate=contract.risk_model.decision_matrix[effect][exposure];decision={AUTO:'ALLOW',AUTO_WITH_GUARDS:'ALLOW_WITH_GUARDS',REQUIRE_EXPLICIT_APPROVAL:'BLOCK_APPROVAL_REQUIRED',PROHIBITED_WITHOUT_OVERRIDE:'BLOCK_OVERRIDE_REQUIRED'}[gate]}return {status:errors.length?'FAIL':'PASS',decision,effective_effect:effect,effective_exposure:exposure,derived_exposure:maxLevel(contrib,EXP),action_gate:gate}}
function invariant(v){const inv=v.input.invariant;if(inv==='all_catalog_ids_have_effect_floor'){const bad=Object.values(catalog).filter(x=>!EFFECT[x.effect_floor]).map(x=>x.id);return {status:bad.length?'FAIL':'PASS',invalid_operations:bad}}if(inv==='deprecated_entries_have_replacement'){const dep=Object.values(catalog).filter(x=>x.lifecycle_status==='deprecated'),bad=dep.filter(x=>typeof x.replacement!=='string'||!x.replacement).map(x=>x.id);return {status:bad.length?'FAIL':'PASS',deprecated_count:dep.length,invalid_operations:bad}}throw Error('unsupported invariant')}
function ptr(o,p){return p.split('/').slice(1).reduce((a,k)=>a?.[k],o)}
let total=0, passed=0;const failures=[];for(const file of ['conformance/golden.json','conformance/invalid.json']){for(const v of read(file).vectors){if(!['routing','execution_boundary','catalog_invariant'].includes(v.kind))continue;total++;const actual=v.kind==='routing'?route(v.input):v.kind==='execution_boundary'?boundary(v.input):invariant(v);let ok=true;for(const p of v.normative_fields){if(JSON.stringify(ptr(actual,p))!==JSON.stringify(ptr(v.expected,p))){ok=false;failures.push({id:v.id,field:p,expected:ptr(v.expected,p),actual:ptr(actual,p)})}}if(ok)passed++}}
console.log(JSON.stringify({format:'universal-agent-docs-javascript-core-conformance-v1',total,passed,failed:total-passed,failures},null,2));process.exit(total===passed?0:1);
